/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "AnnotationTest_constants.h"



const AnnotationTestConstants g_AnnotationTest_constants;

AnnotationTestConstants::AnnotationTestConstants() {
}



