/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "proc_constants.h"

namespace apache { namespace thrift { namespace test {

const procConstants g_proc_constants;

procConstants::procConstants() {
}

}}} // namespace

