/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Recursive_constants.h"



const RecursiveConstants g_Recursive_constants;

RecursiveConstants::RecursiveConstants() {
}



