/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Recursive_CONSTANTS_H
#define Recursive_CONSTANTS_H

#include "Recursive_types.h"



class RecursiveConstants {
 public:
  RecursiveConstants();

};

extern const RecursiveConstants g_Recursive_constants;



#endif
