/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ThriftTest_CONSTANTS_H
#define ThriftTest_CONSTANTS_H

#include "ThriftTest_types.h"

namespace thrift { namespace test {

class ThriftTestConstants {
 public:
  ThriftTestConstants();

  Numberz::type myNumberz;
};

extern const ThriftTestConstants g_ThriftTest_constants;

}} // namespace

#endif
