/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ThriftTest_constants.h"

namespace thrift { namespace test {

const ThriftTestConstants g_ThriftTest_constants;

ThriftTestConstants::ThriftTestConstants() {
  myNumberz = (Numberz::type)1;

}

}} // namespace

