/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "TypedefTest_constants.h"

namespace thrift { namespace test {

const TypedefTestConstants g_TypedefTest_constants;

TypedefTestConstants::TypedefTestConstants() {
}

}} // namespace

