/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef TypedefTest_CONSTANTS_H
#define TypedefTest_CONSTANTS_H

#include "TypedefTest_types.h"

namespace thrift { namespace test {

class TypedefTestConstants {
 public:
  TypedefTestConstants();

};

extern const TypedefTestConstants g_TypedefTest_constants;

}} // namespace

#endif
